In [71]:
import pandas as pd

In [72]:
df=pd.read_csv("/content/drive/MyDrive/Air_Quality_Monitoring_Data_20231016.csv")
df.head()

,Name,GPS,DateTime,NO2,O3_1hr,O3_4hr,O3_8hr,CO,PM10 1 hr,PM2.5 1 hr,...,AQI_CO,AQI_NO2,AQI_O3_1hr,AQI_O3_4hr,AQI_O3_8hr,AQI_PM10,AQI_PM2.5,AQI_Site,Date,Time
0,Monash,"(-35.418302, 149.094018)",02/10/2023 04:00:00 PM,NaN,NaN,NaN,0.032,NaN,24.0,8.1,...,NaN,NaN,NaN,NaN,NaN,49.0,52.0,NaN,02 October 2023,16:00
1,Civic,"(-35.285307, 149.131579)",14/09/2023 06:00:00 AM,NaN,0.002,0.003,0.003,0.0,8.9,6.9,...,0.0,0.0,2.0,4.0,4.0,23.0,27.0,27.0,14 September 2023,06:00
2,Civic,"(-35.285307, 149.131579)",08/09/2023 04:00:00 PM,NaN,NaN,NaN,0.023,NaN,2.7,2.8,...,NaN,NaN,NaN,NaN,NaN,11.0,21.0,21.0,08 September 2023,16:00
3,Civic,"(-35.285307, 149.131579)",04/09/2023 10:00:00 PM,NaN,0.000,0.000,0.011,0.0,21.6,12.2,...,0.0,0.0,0.0,0.0,16.0,21.0,24.0,24.0,04 September 2023,22:00
4,Florey,"(-35.220606, 149.043539)",01/09/2023 05:00:00 PM,NaN,0.034,0.034,0.031,NaN,5.6,1.0,...,NaN,NaN,34.0,43.0,48.0,14.0,24.0,48.0,01 September 2023,17:00

In [73]:
df.describe()

,NO2,O3_1hr,O3_4hr,O3_8hr,CO,PM10 1 hr,PM2.5 1 hr,PM10,PM2.5,AQI_CO,AQI_NO2,AQI_O3_1hr,AQI_O3_4hr,AQI_O3_8hr,AQI_PM10,AQI_PM2.5,AQI_Site
count,210272.000000,292067.000000,304508.000000,304617.000000,217893.000000,274340.000000,222903.000000,274532.000000,223800.000000,217876.000000,211281.000000,291969.000000,304471.000000,147969.000000,274569.000000,223787.000000,308637.000000
mean,0.004862,0.016675,0.016937,0.016793,0.234776,12.352555,8.421752,12.363835,8.424230,2.603889,4.440811,16.538379,21.092107,26.926802,24.626921,33.502634,37.913659
std,0.007948,0.017532,0.010543,0.009573,0.356076,33.641487,33.469914,27.172939,27.149103,3.967593,5.269127,11.069716,13.183157,14.572832,54.340099,108.597281,92.885238
min,-0.001000,0.000000,0.000000,0.000000,-0.060000,-55.000000,-38.000000,-2.000000,-4.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,-3.000000,-15.000000,0.000000
25%,0.000000,0.007000,0.009000,0.010000,0.080000,4.000000,2.000000,6.000000,3.000000,1.000000,1.000000,7.000000,11.000000,17.000000,12.000000,14.000000,22.000000
50%,0.002000,0.017000,0.017000,0.017000,0.140000,8.000000,5.000000,9.000000,5.000000,2.000000,3.000000,17.000000,22.000000,27.000000,18.000000,21.000000,29.000000
75%,0.007000,0.024000,0.024000,0.023000,0.270000,14.000000,9.000000,14.000000,8.000000,3.000000,7.000000,24.000000,30.000000,37.000000,27.000000,33.000000,38.000000
max,0.271000,1.916000,0.118000,0.107000,22.000000,2714.000000,2496.000000,1216.000000,1296.000000,244.000000,143.000000,127.000000,147.000000,164.000000,2432.000000,5185.000000,5185.000000

In [74]:
df.isna().sum()

Name               0
GPS                0
DateTime           0
NO2            98479
O3_1hr         16684
O3_4hr          4243
O3_8hr          4134
CO             90858
PM10 1 hr      34411
PM2.5 1 hr     85848
PM10           34219
PM2.5          84951
AQI_CO         90875
AQI_NO2        97470
AQI_O3_1hr     16782
AQI_O3_4hr      4280
AQI_O3_8hr    160782
AQI_PM10       34182
AQI_PM2.5      84964
AQI_Site         114
Date               0
Time               0
dtype: int64

In [75]:
len(df)

308751

In [76]:
len(df.dropna())

72181

In [77]:
df.dtypes

Name           object
GPS            object
DateTime       object
NO2           float64
O3_1hr        float64
O3_4hr        float64
O3_8hr        float64
CO            float64
PM10 1 hr     float64
PM2.5 1 hr    float64
PM10          float64
PM2.5         float64
AQI_CO        float64
AQI_NO2       float64
AQI_O3_1hr    float64
AQI_O3_4hr    float64
AQI_O3_8hr    float64
AQI_PM10      float64
AQI_PM2.5     float64
AQI_Site      float64
Date           object
Time           object
dtype: object

In [78]:
len(df.dropna(thresh=17))

256897

In [79]:
di = df.set_index("Name")
di.head()
len(di.drop('Civic'))

196617

Dropping Civic, since column has null values for NO2 and CO
Dropping Florey, since data is not available from 2011 to 2014

In [80]:
di=di.drop('Civic')
di=di.drop('Florey')

In [81]:
len(di)

112133

In [82]:
len(di.dropna(thresh=17))

107087

In [83]:
di=di.dropna(thresh=17)

In [84]:
di.describe()

,NO2,O3_1hr,O3_4hr,O3_8hr,CO,PM10 1 hr,PM2.5 1 hr,PM10,PM2.5,AQI_CO,AQI_NO2,AQI_O3_1hr,AQI_O3_4hr,AQI_O3_8hr,AQI_PM10,AQI_PM2.5,AQI_Site
count,104125.000000,104324.000000,107054.000000,107067.000000,103687.000000,106150.000000,71903.000000,106437.000000,72052.000000,103687.000000,104106.000000,104323.000000,107054.000000,107067.000000,106437.000000,72052.000000,107028.000000
mean,0.004392,0.018120,0.018037,0.017937,0.229930,11.878102,9.266871,11.834771,9.246796,2.556299,4.021257,17.738984,22.461272,27.552402,23.569454,36.792539,41.004251
std,0.005853,0.025498,0.011034,0.009995,0.384287,30.250739,35.748162,24.189501,29.388893,4.277105,5.285441,11.627652,13.798988,15.385206,48.377251,117.551488,96.254862
min,-0.001000,0.000000,0.000000,0.000000,0.000000,-25.000000,-20.000000,-2.000000,-2.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,-3.000000,-6.000000,3.000000
25%,0.000000,0.008000,0.009000,0.011000,0.070000,4.000000,2.000000,6.000000,3.200000,1.000000,0.000000,8.000000,12.000000,16.000000,11.000000,14.000000,24.000000
50%,0.002000,0.018000,0.019000,0.018000,0.130000,8.000000,5.000000,9.000000,5.000000,1.000000,2.000000,18.000000,23.000000,28.000000,18.000000,22.000000,32.000000
75%,0.007000,0.026000,0.026000,0.025000,0.260000,14.000000,10.000000,14.000000,9.000000,3.000000,6.000000,26.000000,32.000000,38.000000,27.000000,36.000000,41.000000
max,0.116000,1.916000,0.118000,0.107000,22.000000,1894.000000,1926.000000,1216.000000,1296.000000,244.000000,97.000000,127.000000,147.000000,164.000000,2432.000000,5185.000000,5185.000000

In [85]:
di.head()

,GPS,DateTime,NO2,O3_1hr,O3_4hr,O3_8hr,CO,PM10 1 hr,PM2.5 1 hr,PM10,...,AQI_CO,AQI_NO2,AQI_O3_1hr,AQI_O3_4hr,AQI_O3_8hr,AQI_PM10,AQI_PM2.5,AQI_Site,Date,Time
Name,,,,,,,,,,,,,,,,,,,,,
Monash,"(-35.418302, 149.094018)",28/06/2023 04:00:00 PM,NaN,NaN,0.008,0.006,0.23,9.00,5.40,7.10,...,3.0,NaN,NaN,10.0,9.0,14.0,19.0,19.0,28 June 2023,16:00
Monash,"(-35.418302, 149.094018)",04/10/2023 01:00:00 PM,0.005,0.025,0.023,0.022,0.00,16.52,6.29,18.37,...,0.0,4.0,25.0,29.0,34.0,36.0,25.0,36.0,04 October 2023,13:00:00
Monash,"(-35.418302, 149.094018)",13/03/2019 01:00:00 AM,0.000,0.019,0.022,0.026,0.04,12.00,-4.00,11.00,...,0.0,0.0,19.0,27.0,40.0,21.0,16.0,27.0,13 March 2019,01:00
Monash,"(-35.418302, 149.094018)",12/01/2019 04:00:00 PM,NaN,NaN,0.042,0.040,0.36,11.00,0.00,8.00,...,4.0,NaN,NaN,53.0,62.0,15.0,15.0,53.0,12 January 2019,16:00
Monash,"(-35.418302, 149.094018)",04/10/2023 02:00:00 PM,0.003,0.024,0.022,0.022,0.00,14.41,6.79,18.19,...,0.0,3.0,24.0,27.0,35.0,36.0,25.0,36.0,04 October 2023,14:00:00

Droping GPS as city Name is already there.
Droping DateTime  as city Date and Time seperately exist.

In [86]:

di = di.drop(columns=["GPS", "DateTime"])

convert merge date and time column into column DateTime (DataTime data type)

In [87]:
di['DateTime']=pd.to_datetime(di['Date'] + ' ' + di['Time'])

In [88]:
di = di.drop(columns=["Date", "Time"])

In [89]:
di=di.sort_values(by=['DateTime'])
di.head()

,NO2,O3_1hr,O3_4hr,O3_8hr,CO,PM10 1 hr,PM2.5 1 hr,PM10,PM2.5,AQI_CO,AQI_NO2,AQI_O3_1hr,AQI_O3_4hr,AQI_O3_8hr,AQI_PM10,AQI_PM2.5,AQI_Site,DateTime
Name,,,,,,,,,,,,,,,,,,
Monash,0.021,0.008,0.027,0.033,0.15,NaN,NaN,15.0,NaN,2.0,18.0,8.0,34.0,50.0,30.0,NaN,34.0,2011-01-01 21:00:00
Monash,0.011,0.016,0.021,0.029,0.18,NaN,NaN,15.0,NaN,2.0,9.0,16.0,27.0,45.0,31.0,NaN,31.0,2011-01-01 22:00:00
Monash,0.012,0.011,0.016,0.025,0.21,NaN,NaN,15.0,NaN,2.0,10.0,11.0,19.0,39.0,31.0,NaN,31.0,2011-01-01 23:00:00
Monash,0.002,0.028,0.014,0.024,0.21,NaN,NaN,16.0,NaN,2.0,6.0,19.0,17.0,38.0,31.0,NaN,31.0,2011-01-02 00:00:00
Monash,0.002,0.028,0.019,0.023,0.21,8.0,NaN,15.0,NaN,2.0,2.0,28.0,23.0,35.0,30.0,NaN,30.0,2011-01-02 01:00:00

Identify Outliers using IQR

In [90]:
def id_outliers(col):
            Q1 = col.quantile(0.25)
            Q3 = col.quantile(0.75)
            IQR = Q3-Q1
            lBound = Q1-(1.5*IQR)
            uBound = Q3+(1.5*IQR)
            outlier = ((col < lBound) | (col > uBound))
            return outlier.sum()
outliers_count = di.apply(id_outliers)
print("\nNumber of outliers in each column:")
print(outliers_count)

Number of outliers in each column:
NO2            4920
O3_1hr          498
O3_4hr          457
O3_8hr          616
CO            10478
PM10 1 hr      6558
PM2.5 1 hr     5751
PM10           3684
PM2.5          6851
AQI_CO         9394
AQI_NO2        5073
AQI_O3_1hr      403
AQI_O3_4hr      551
AQI_O3_8hr      616
AQI_PM10       4029
AQI_PM2.5      6916
AQI_Site       8189
DateTime          0
dtype: int64

In [91]:
def drop_outlier(col):
            Q1 = col.quantile(0.25)
            Q3 = col.quantile(0.75)
            IQR = Q3-Q1
            lBound = Q1-(1.5*IQR)
            uBound = Q3+(1.5*IQR)
            drop_ol= col.apply(lambda ol: None if (ol < lBound) or (ol > uBound) else ol)
            return drop_ol
di = di.apply(drop_outlier)

Replace null value with valid previous value.

In [92]:
di=di.fillna(method='ffill')

replace the remaining null values with next valid value.

In [93]:
di=di.fillna(method='bfill')

In [94]:
di.isna().sum()

NO2           0
O3_1hr        0
O3_4hr        0
O3_8hr        0
CO            0
PM10 1 hr     0
PM2.5 1 hr    0
PM10          0
PM2.5         0
AQI_CO        0
AQI_NO2       0
AQI_O3_1hr    0
AQI_O3_4hr    0
AQI_O3_8hr    0
AQI_PM10      0
AQI_PM2.5     0
AQI_Site      0
DateTime      0
dtype: int64

In [95]:
di.head()

,NO2,O3_1hr,O3_4hr,O3_8hr,CO,PM10 1 hr,PM2.5 1 hr,PM10,PM2.5,AQI_CO,AQI_NO2,AQI_O3_1hr,AQI_O3_4hr,AQI_O3_8hr,AQI_PM10,AQI_PM2.5,AQI_Site,DateTime
Name,,,,,,,,,,,,,,,,,,
Monash,0.011,0.008,0.027,0.033,0.15,8.0,14.0,15.0,17.0,2.0,9.0,8.0,34.0,50.0,30.0,67.0,34.0,2011-01-01 21:00:00
Monash,0.011,0.016,0.021,0.029,0.18,8.0,14.0,15.0,17.0,2.0,9.0,16.0,27.0,45.0,31.0,67.0,31.0,2011-01-01 22:00:00
Monash,0.012,0.011,0.016,0.025,0.21,8.0,14.0,15.0,17.0,2.0,10.0,11.0,19.0,39.0,31.0,67.0,31.0,2011-01-01 23:00:00
Monash,0.002,0.028,0.014,0.024,0.21,8.0,14.0,16.0,17.0,2.0,6.0,19.0,17.0,38.0,31.0,67.0,31.0,2011-01-02 00:00:00
Monash,0.002,0.028,0.019,0.023,0.21,8.0,14.0,15.0,17.0,2.0,2.0,28.0,23.0,35.0,30.0,67.0,30.0,2011-01-02 01:00:00